version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: go-template
      
    ports:
      - 3306:3306

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
