package routes

import (
	swagger "github.com/arsmn/fiber-swagger/v2"
	_ "github.com/arsmn/fiber-swagger/v2/example/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/gofiber/fiber/v2"
)

// RegisterSwaggerRoutes method to register App router
func RegisterSwaggerRoutes(app *fiber.App) {
	app.Get("/swagger/*", swagger.Handler)
}
